services:
  postgres:
    image: postgres:17.5
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: mq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbit_mq_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  bot:
    depends_on:
      rabbitmq:
        condition: service_healthy
    image: bot:latest
    container_name: bot
    hostname: bot
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s   
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${APP_ENV}
      - BOT_URL=${BOT_URL}
      - DADATA_API_KEY=${DADATA_API_KEY}
      - DADATA_SECRET_KEY=${DADATA_SECRET_KEY}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - RABBIT_MQ_HOST=${RABBIT_MQ_HOST}
      - RABBIT_MQ_PORT=${RABBIT_MQ_PORT}
      - RABBIT_MQ_USER=${RABBIT_MQ_USER}
      - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}    
      - LOG_LEVEL=${LOG_LEVEL}    
    volumes:
      - bot_data:/data
      - bot_logs:/app/logs
    ports:
      - 8080:8080
    networks:
      - app-network

  crawler:
    depends_on:
      rabbitmq:
        condition: service_healthy
    image: crawler:latest
    container_name: crawler
    hostname: crawler
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8180/actuator/health || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${APP_ENV}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - RABBIT_MQ_HOST=${RABBIT_MQ_HOST}
      - RABBIT_MQ_PORT=${RABBIT_MQ_PORT}
      - RABBIT_MQ_USER=${RABBIT_MQ_USER}
      - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL}      
    volumes:
      - crawler_data:/data
      - crawler_logs:/app/logs
    ports:
      - 8180:8180
    networks:
      - app-network
    
volumes:
  postgres_data:
  rabbit_mq_data:
  bot_data:
  bot_logs:
  crawler_data:
  crawler_logs:

networks:
  app-network:
    driver: bridge