services:
  postgres:
    image: postgres:17.5
    container_name: postgres-17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
    - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbit_mq_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  bot:
    depends_on:
      rabbitmq:
        condition: service_healthy
    image: bot:latest
    container_name: svet_bot
    hostname: bot
    restart: always
    environment:
      - BOT_URL=${BOT_URL}
      - DADATA_API_KEY=${DADATA_API_KEY}
      - DADATA_SECRET_KEY=${DADATA_SECRET_KEY}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - RABBIT_MQ_HOST=${RABBIT_MQ_HOST}
      - RABBIT_MQ_PORT=${RABBIT_MQ_PORT}
      - RABBIT_MQ_USER=${RABBIT_MQ_USER}
      - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}    
    volumes:
      - bot_data:/data
    ports:
      - 8080:8080
    networks:
      - app-network

  crawler:
    depends_on:
      rabbitmq:
        condition: service_healthy
    image: crawler:latest
    container_name: svet_crawler
    hostname: crawler
    restart: always
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - RABBIT_MQ_HOST=${RABBIT_MQ_HOST}
      - RABBIT_MQ_PORT=${RABBIT_MQ_PORT}
      - RABBIT_MQ_USER=${RABBIT_MQ_USER}
      - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}
    volumes:
      - crawler_data:/data
    ports:
      - 8180:8180
    networks:
      - app-network

volumes:
  postgres_data:
  rabbit_mq_data:
  bot_data:
  crawler_data:

networks:
  app-network:
    driver: bridge